name: Essay
favicon: null
layout_spectrum: 0.35277426219545305
typography_spectrum: 0.40428198385052383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5363456862978637
  lightness: 0.49232075177133083
  saturation: 0.12232939363457263
  rhythmicContrast: 0.18927437881939113
purpose: []
